// Bundles the standalone 2D runtime: node scripts/build-runtime.mjs [--out=path] -> runtime/gamboligy-character2d.js
//   --check: rebuild to a temp file and exit 1 if the committed bundle is stale (core/render2d changed since)
import { build } from 'esbuild';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
const check = process.argv.includes('--check'), target = 'runtime/gamboligy-character2d.js';
const outfile = check ? path.join(os.tmpdir(), `runtime-check-${process.pid}.js`) : (process.argv.find((a) => a.startsWith('--out='))?.slice(6) || target);
await build({ entryPoints: ['runtime/src/index.js'], bundle: true, format: 'esm', target: 'es2020', outfile,
  banner: { js: '// Gamboligy 2D character runtime (gamboligy.character2d-runtime/1.0). Generated by scripts/build-runtime.mjs from viewer/js/art2d/core.js + render2d.js — edit those, not this file.' },
  legalComments: 'none' });
if (check) {
  const same = fs.readFileSync(outfile, 'utf8') === fs.readFileSync(target, 'utf8'); fs.rmSync(outfile);
  console.log(same ? 'runtime bundle is up to date' : 'runtime bundle is STALE: run node scripts/build-runtime.mjs');
  process.exit(same ? 0 : 1);
}
console.log(outfile);
