// Bundles the standalone 2D runtime: node scripts/build-runtime.mjs -> runtime/gamboligy-character2d.js
import { build } from 'esbuild';
await build({ entryPoints: ['runtime/src/index.js'], bundle: true, format: 'esm', target: 'es2020', outfile: 'runtime/gamboligy-character2d.js',
  banner: { js: '// Gamboligy 2D character runtime (gamboligy.character2d-runtime/1.0). Generated by scripts/build-runtime.mjs from viewer/js/art2d/core.js + render2d.js — edit those, not this file.' },
  legalComments: 'none' });
console.log('runtime/gamboligy-character2d.js');
