// Visual QA pass over clips: contact sheets (whole clip + flagged times), heuristic flags, contact-art
// coverage, hand appearances used, and a per-clip status table that keeps mathematical validity,
// missing art, auto-flags and the human visual review separate.
//   node scripts/qa-2d.mjs [--project=characters2d/aureate_knight/character.json] [--skin=default] [--all] [--out=validation/qa]
import { chromium } from 'playwright-core';
import fs from 'node:fs';
import { startServer, CHROME, CHROME_ARGS } from './serve.mjs';

const arg = (k, d = null) => { const a = process.argv.find((x) => x.startsWith(`--${k}=`)); return a ? a.slice(k.length + 3) : d; };
const projectPath = arg('project', 'characters2d/aureate_knight/character.json'), skin = arg('skin', 'default'), OUT = arg('out', 'validation/qa');
const ONLY = arg('clips') ? arg('clips').split(',') : null;
const HERO = ['idle', 'hover_sword_vigil', 'sword_2h_idle', 'sword_2h_slash', 'knight_salute'], REGRESSION = ['walk_in_place', 'finger_tests_2d', 'contact_detonator_2d'];
fs.mkdirSync(OUT, { recursive: true });
const server = await startServer(0);
const browser = await chromium.launch({ executablePath: CHROME, headless: true, args: [...CHROME_ARGS, '--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
const errors = []; page.on('pageerror', (e) => errors.push(e.message));
await page.goto(`http://127.0.0.1:${server.address().port}/viewer/knight.html?art=2d`);
await page.waitForFunction(() => window.art2d?.editor?.ready, null, { timeout: 120000 });
await page.evaluate(async (p) => { await art2d.openURL('../' + p); await art2d.editor.ready; }, projectPath);
const clips = ONLY || (process.argv.includes('--all') ? await page.evaluate(() => art2d.project.clips.map((c) => c.name)) : [...HERO, ...REGRESSION]);
const results = [];
for (const name of clips) {
  const r = await page.evaluate(async ({ name, skin }) => {
    const qa = await import('./js/art2d/visualqa.js'), hv = await import('./js/art2d/handviews.js'), { Rig } = await import('./js/art2d/core.js');
    const ed = art2d.editor; art2d.setSkin(skin);
    if (!art2d.project.clips.some((c) => c.name === name)) return null;
    const a = await art2d.runQA(name);
    const png = await art2d.qaSheet(name);
    const contacts = await qa.contactArt(art2d.project, art2d.store, name, { skin, renderer: ed.qaRenderer });
    const rig = new Rig(art2d.project); rig.setSkin(skin);
    const hands = Object.fromEntries(['L', 'R'].map((s) => { const used = hv.setsUsed(rig, rig.clips.get(name), s); return [s, { used, minHoldFrames: Math.round(hv.minHoldSeconds(used) * 30) }]; }));
    const st = qa.clipStatus(art2d.project, name, a, { skin });
    const b64 = btoa(Array.from(png, (c) => String.fromCharCode(c)).join(''));
    return { name, status: st, summary: a.summary, info: a.info, frameFlags: a.frameFlags, flags: a.flags.map(({ severity, ...f }) => ({ ...f, severity: +severity.toFixed(2) })), contacts, hands, sheet: b64 };
  }, { name, skin });
  if (!r) continue;
  fs.writeFileSync(`${OUT}/${name}.png`, Buffer.from(r.sheet, 'base64')); delete r.sheet;
  results.push(r);
  console.log(`${name}: ${r.status.autoFlags} flags ${JSON.stringify(r.summary)} info ${JSON.stringify(r.info)} · contacts ${r.contacts.map((c) => `${c.contact} ${c.bothPct}%`).join(', ') || '—'} · review ${r.status.visualReview}`);
}
fs.writeFileSync(`${OUT}/qa.json`, JSON.stringify({ project: projectPath, skin, results, errors }, null, 1));
const md = [`# Visual QA — ${projectPath} (skin "${skin}")`, '', 'Generated by `node scripts/qa-2d.mjs`. Flags are heuristics (thresholds in `viewer/js/art2d/visualqa.js`), not verdicts; the',
  'visual review column is a human decision recorded in the project (`visualQA.review`). Contact sheets: `' + OUT + '/<clip>.png` (start, end, even steps, events, key changes and the worst flags).', '',
  '| clip | math | art | auto-flags (open) | contact art (frames with hand + prop art at the contact) | hand appearances (min hold) | visual review |', '|---|---|---|---|---|---|---|',
  ...results.map((r) => `| ${r.name} | ${r.status.math} | ${r.status.missingArt} | ${r.status.autoFlags}${Object.keys(r.summary).length ? ' (' + Object.entries(r.summary).map(([k, v]) => `${k} ${v}`).join(', ') + ')' : ''} | ${r.contacts.map((c) => `${c.contact} ${c.bothPct}%`).join('<br>') || '—'} | ${['L', 'R'].map((s) => `${s}: ${r.hands[s].used.length} (${Number.isFinite(r.hands[s].minHoldFrames) ? r.hands[s].minHoldFrames + ' fr' : 'static'})`).join(', ')} | ${r.status.visualReview}${r.status.reviewNote ? ': ' + r.status.reviewNote.replace(/\|/g, '/') : ''} |`),
  '', '## Flags per clip', '', 'Ranged: consecutive frames of one finding are one line (from–to, frame count, worst value). ⚠ open · ✓ excepted (reason recorded in the project) · ℹ info (not counted: not visible by construction).', '',
  ...results.flatMap((r) => [`### ${r.name}`, '', ...(r.flags.length ? [...r.flags].sort((a, b) => (!!a.info - !!b.info) || (!!a.exception - !!b.exception) || b.severity - a.severity).slice(0, 25).map((f) => `- ${f.info ? 'ℹ' : f.exception ? '✓' : '⚠'} ${f.to > f.from ? `${f.from.toFixed(2)}–${f.to.toFixed(2)} s (${f.frames} samples, worst ${f.t.toFixed(2)} s)` : `${f.t.toFixed(2)} s`} · ${f.kind} · ${f.target} = ${f.value} ${f.unit} (threshold ${f.threshold})${f.exception ? ` — exception: ${f.exception.reason}` : ''}${f.info ? ` — ${f.info}` : ''}`) : ['- none']), ...(r.flags.length > 25 ? [`- … ${r.flags.length - 25} more in qa.json`] : []), '']), ''];
fs.writeFileSync(`${OUT}/QA-REPORT.md`, md.join('\n'));
await browser.close(); server.close();
if (errors.length) { console.log('page errors:', errors.slice(0, 5)); process.exit(1); }
